class AppError(Exception):
    def __init__(self, status_code: int, code: str, message: str) -> None:
        self.status_code = status_code
        self.code = code
        self.message = message
        super().__init__(message)


USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
UNAUTHENTICATED = "UNAUTHENTICATED"
CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS"
CATEGORY_IN_USE = "CATEGORY_IN_USE"
TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
TRANSACTION_TYPE_MISMATCH = "TRANSACTION_TYPE_MISMATCH"
BUDGET_NOT_FOUND = "BUDGET_NOT_FOUND"
BUDGET_ALREADY_EXISTS = "BUDGET_ALREADY_EXISTS"
BUDGET_REQUIRES_EXPENSE_CATEGORY = "BUDGET_REQUIRES_EXPENSE_CATEGORY"
INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
INVALID_ANALYTICS_QUERY = "INVALID_ANALYTICS_QUERY"
